#!/usr/bin/env ruby

require 'rubygems'
require 'fileutils'
require 'sinatra'

BASE_DIR = File.dirname(__FILE__)
PID_FILE = "#{BASE_DIR}/.github-listener.pid"

# Check to see if another daemon is running.
# If so, kill it.
if File.exists? PID_FILE
  pid = File.read(PID_FILE).to_i
  begin
    Process.kill "TERM", pid
  rescue Errno::ESRCH
  end
  sleep 6
end
File.open(PID_FILE, "w") {|f| f.write($$)}

post '/update/:user/:repo' do

  repo = "#{BASE_DIR}/#{params[:user]}/#{params[:repo]}.git"

  if File.directory? repo
    %x{git --git-dir #{repo} fetch --all --prune}
    200
  else
    404
  end
end

not_found do
  404
end
